<template>
  <NuxtLayout name="layout-documents">
    <main class="w-full min-h-screen | pt-8 pb-40 px-12 | border-r">
      <DocsBreadcrumb name="Introduction" link="/documents/introduction" />
      <DocsSection id="WhatIsMM">
        <h2 class="text-3xl font-bold">What is MM?</h2>
        <p class="leading-relaxed">
          MM(Mark Up Manager) is an innovative tool that allows for more
          effective design and management of HTML and CSS. True to its name,
          'Mark Up Manager' assists in the management of code markup, providing
          a GUI for intuitive and swift design.
        </p>
        <br />
        <p>
          <span class="font-bold">Convenient Layout Design</span><br />
          MM allows easy manipulation of website layouts through GUI controls
          and keyboard shortcuts. Leveraging responsive attributes, you can
          effortlessly construct websites that adapt seamlessly to various
          devices, including mobile platforms.
        </p>
        <br />
        <p>
          <span class="font-bold">Widget Creation Feature</span><br />
          You can create a variety of widgets by directly writing HTML and CSS.
          Build layouts and register widgets in specific areas with ease,
          offering a high level of customization.
        </p>
        <br />
        <p>
          <span class="font-bold">Efficient CSS generation</span><br />
          Utilizing various properties, diverse styles are automatically formed,
          allowing users to easily implement their desired designs.
        </p>
        <br />
        <p>
          <span class="font-bold">Workspace Configuration</span><br />
          Utilize the &lt;iframe&gt; element to effortlessly set up a personal
          workspace. Efficiently organize various working environments required
          for your projects.
        </p>
        <br />
        <p>
          <span class="font-bold"> Comment and Collaboration Features </span>
          <br />
          Write comments to exchange opinions with other users. Strengthen team
          collaboration and efficiently manage feedback on projects.
        </p>
        <br />
        <p>
          MM provides an intuitive and collaboration-centric environment for
          both web designers and developers. Reduce the hassle of code writing
          and complete the web design process more efficiently.
        </p>
      </DocsSection>
      <DocsSection id="History">
        <h2 class="text-3xl font-bold">History</h2>
        <p>
          MM(Markup Manager) is a service targeting key stakeholders in web
          development, particularly planners, markup developers, and front-end
          engineers. This service has been developed to streamline the web
          development process.
        </p>
        <br />
        <p>
          <span class="font-bold">Integration of Deliverables</span>
          <br />
          In the web development process, deliverables generated by each
          stakeholder have different formats and content. Planners create
          planning documents, markup developers write HTML/CSS, and front-end
          engineers develop projects using React or Vue. Over time, the evolving
          nature of each deliverable makes project maintenance challenging. MM
          addresses this issue by integrating each deliverable and maintaining
          MM's data up-to-date, providing consistent reference materials for
          ease of maintenance.
        </p>
        <br />
        <p>
          <span class="font-bold">Conceptual Clarity</span>
          <br />
          There are instances where team members involved in web development
          lack a common understanding. MM enhances understanding by allowing
          users to directly manipulate screens and providing experiences that
          elevate the intuition for essential web development concepts, such as
          'layouts.' This facilitates effective collaboration among project team
          members who share the same vision and understanding.
        </p>
        <br />
        <p>
          <span class="font-bold">Componentization</span>
          <br />
          The majority of front-end engineers utilize technologies like React or
          Vue for component-based development (CBD). Reflecting this trend, MM
          supports planners and markup developers in conceptualizing screens in
          a component-oriented manner.
        </p>
      </DocsSection>
    </main>
  </NuxtLayout>
</template>

<script setup lang="ts">
import DocsBreadcrumb from '~/components/DocsBreadcrumb.vue'
import DocsSection from '~/components/DocsSection.vue'

useSeoMeta({
  title: 'MM-GUIDE > Documents > Introduction',
  ogTitle: 'MM-GUIDE > Documents > Introduction',
  description: 'MM-GUIDE Introduction',
  ogDescription: 'MM-GUIDE Introduction',
})
</script>

<style></style>
